// =============================================================================
// common/ring.rs — parameter-invariant ring arithmetic, FIPS 204.
//
// Everything here is identical across EVERY ML-DSA security level (44/65/87)
// per the standard: N=256, Q=8380417, D=13 and the NTT are fixed constants
// of the ring R_q = Z_q[x]/(x^n+1), independent of the module rank (K, L)
// or any of the per-level bounds (ETA, TAU, GAMMA1, GAMMA2, OMEGA). This
// module holds that shared core exactly once so it is never re-typed (and
// risking re-introducing a transcription bug) per parameter set.
//
// Parameter-*dependent* polynomial operations (decompose/hints, rejection
// sampling, all pack/unpack routines whose bit-widths depend on ETA/GAMMA1/
// GAMMA2/OMEGA) live per-variant instead, generated by `ml_dsa_impl!` in
// `dsa/ml_dsa/core.rs` — see that file's header comment for why.
// =============================================================================

pub const N: usize = 256; // FIPS 204 Table 1 (same for all parameter sets)
pub const Q: i32 = 8_380_417; // FIPS 204 §2.3 (same for all parameter sets)
pub const D: i32 = 13; // FIPS 204 Table 1 (same for all parameter sets)

/// q⁻¹ mod 2³². Algorithm 49 line 1. q·QINV ≡ 1 (mod 2³²).
pub const QINV: i32 = 58_728_449;

/// R = 2³² mod q. (Appendix A)
pub const MONT: i32 = 4_193_792;

/// Zeta table — FIPS 204 Appendix B (p.51), verbatim. Depends only on
/// N=256 and Q, so it is identical for every ML-DSA parameter set.
pub const ZETAS: [i32; 256] = [
    0, 4808194, 3765607, 3761513, 5178923, 5496691, 5234739, 5178987, 7778734, 3542485, 2682288,
    2129892, 3764867, 7375178, 557458, 7159240, 5010068, 4317364, 2663378, 6705802, 4855975,
    7946292, 676590, 7044481, 5152541, 1714295, 2453983, 1460718, 7737789, 4795319, 2815639,
    2283733, 3602218, 3182878, 2740543, 4793971, 5269599, 2101410, 3704823, 1159875, 394148,
    928749, 1095468, 4874037, 2071829, 4361428, 3241972, 2156050, 3415069, 1759347, 7562881,
    4805951, 3756790, 6444618, 6663429, 4430364, 5483103, 3192354, 556856, 3870317, 2917338,
    1853806, 3345963, 1858416, 3073009, 1277625, 5744944, 3852015, 4183372, 5157610, 5258977,
    8106357, 2508980, 2028118, 1937570, 4564692, 2811291, 5396636, 7270901, 4158088, 1528066,
    482649, 1148858, 5418153, 7814814, 169688, 2462444, 5046034, 4213992, 4892034, 1987814,
    5183169, 1736313, 235407, 5130263, 3258457, 5801164, 1787943, 5989328, 6125690, 3482206,
    4197502, 7080401, 6018354, 7062739, 2461387, 3035980, 621164, 3901472, 7153756, 2925816,
    3374250, 1356448, 5604662, 2683270, 5601629, 4912752, 2312838, 7727142, 7921254, 348812,
    8052569, 1011223, 6026202, 4561790, 6458164, 6143691, 1744507, 1753, 6444997, 5720892, 6924527,
    2660408, 6600190, 8321269, 2772600, 1182243, 87208, 636927, 4415111, 4423672, 6084020, 5095502,
    4663471, 8352605, 822541, 1009365, 5926272, 6400920, 1596822, 4423473, 4620952, 6695264,
    4969849, 2678278, 4611469, 4829411, 635956, 8129971, 5925040, 4234153, 6607829, 2192938,
    6653329, 2387513, 4768667, 8111961, 5199961, 3747250, 2296099, 1239911, 4541938, 3195676,
    2642980, 1254190, 8368000, 2998219, 141835, 8291116, 2513018, 7025525, 613238, 7070156,
    6161950, 7921677, 6458423, 4040196, 4908348, 2039144, 6500539, 7561656, 6201452, 6757063,
    2105286, 6006015, 6346610, 586241, 7200804, 527981, 5637006, 6903432, 1994046, 2491325,
    6987258, 507927, 7192532, 7655613, 6545891, 5346675, 8041997, 2647994, 3009748, 5767564,
    4148469, 749577, 4357667, 3980599, 2569011, 6764887, 1723229, 1665318, 2028038, 1163598,
    5011144, 3994671, 8368538, 7009900, 3020393, 3363542, 214880, 545376, 7609976, 3105558,
    7277073, 508145, 7826699, 860144, 3430436, 140244, 6866265, 6195333, 3123762, 2358373, 6187330,
    5365997, 6663603, 2926054, 7987710, 8077412, 3531229, 4405932, 4606686, 1900052, 7598542,
    1054478, 7648983,
];

use sha3::{
    digest::{ExtendableOutput, Update, XofReader},
    Shake128, Shake256,
};

// =============================================================================
// 1. Modular arithmetic helpers
// =============================================================================

/// Montgomery reduction — Algorithm 49.
///
/// Input: a with |a| ≤ 2^31 · q
/// Output: r such that r ≡ a · 2^{−32} (mod q), |r| < 2q
#[inline(always)]
pub fn montgomery_reduce(a: i64) -> i32 {
    // Line 1: QINV = 58728449  (q^{-1} mod 2^32, positive i32)
    // Line 2: t = (a mod 2^32) · QINV  mod 2^32
    let t = (a as i32).wrapping_mul(QINV);
    // Line 3: r = (a − t·q) / 2^32
    ((a - (t as i64) * (Q as i64)) >> 32) as i32
}

/// Full reduce into [0, q−1].
#[inline(always)]
pub fn freeze(a: i32) -> i32 {
    let r = a % Q;
    if r < 0 {
        r + Q
    } else {
        r
    }
}

/// Centred reduce: map a into (−q/2, q/2].
#[inline(always)]
pub fn centered(a: i32) -> i32 {
    let r = freeze(a);
    if r > (Q - 1) / 2 {
        r - Q
    } else {
        r
    }
}

// =============================================================================
// 2. Rounding functions — FIPS 204 §7.4
// =============================================================================


/// Power2Round — Algorithm 35.
///

// =============================================================================
// 2. NTT and inverse NTT — FIPS 204 Algorithms 41 & 42
// =============================================================================

/// Forward NTT — Algorithm 41.
///
/// Input:  w[0..255] ∈ Z_q
/// Output: ŵ[0..255] ∈ T_q   (in-place)
pub fn ntt(w: &mut [i32; N]) {
    let mut m: usize = 0; // Alg 41 line 4 (m ← 0)
    let mut len: usize = 128; // Alg 41 line 5

    while len >= 1 {
        // Alg 41 line 6
        let mut start: usize = 0; // Alg 41 line 7
        while start < N {
            // Alg 41 line 8
            m += 1; // Alg 41 line 9
            let z = ZETAS[m] as i64; // Alg 41 line 10
            for j in start..start + len {
                // Alg 41 line 11
                // Alg 41 lines 12-14
                let t = ((z * w[j + len] as i64).rem_euclid(Q as i64)) as i32;
                w[j + len] = (w[j] - t).rem_euclid(Q);
                w[j] = (w[j] + t).rem_euclid(Q);
            }
            start += 2 * len; // Alg 41 line 16
        }
        len >>= 1; // Alg 41 line 18
    }
}

/// Inverse NTT — Algorithm 42.
///
/// Input:  ŵ[0..255] ∈ T_q
/// Output: w[0..255] ∈ R_q   (in-place)
pub fn invntt(w: &mut [i32; N]) {
    let mut m: usize = 256; // Alg 42 line 4
    let mut len: usize = 1; // Alg 42 line 5

    while len < N {
        // Alg 42 line 6
        let mut start: usize = 0; // Alg 42 line 7
        while start < N {
            // Alg 42 line 8
            m -= 1; // Alg 42 line 9
            let z = (-(ZETAS[m] as i64)).rem_euclid(Q as i64); // Alg 42 line 10
            for j in start..start + len {
                // Alg 42 line 11
                let t = w[j]; // Alg 42 line 12
                w[j] = (t + w[j + len]).rem_euclid(Q); // Alg 42 line 13
                w[j + len] = (t - w[j + len]).rem_euclid(Q); // Alg 42 line 14
                w[j + len] = ((z * w[j + len] as i64).rem_euclid(Q as i64)) as i32;
                // Alg 42 line 15
            }
            start += 2 * len; // Alg 42 line 17
        }
        len <<= 1; // Alg 42 line 19
    }

    // Alg 42 lines 21-24: multiply each coefficient by f = 256^{-1} mod q = 8347681
    let f: i64 = 8_347_681;
    for j in 0..N {
        w[j] = ((f * w[j] as i64).rem_euclid(Q as i64)) as i32;
    }
}


// =============================================================================
// 3. Zeroization
// =============================================================================

/// Zero out a raw secret byte buffer (seeds, key bytes, hashes derived from
/// secret material, etc.) using volatile writes so the compiler cannot
/// eliminate the clear as a dead store.
///
/// PATCHED: added as part of the zeroization hardening pass — call this on
/// every `[u8; N]` that holds secret seed / key material once it is no
/// longer needed (see mldsa44.rs for call sites).
#[inline(always)]
pub fn zeroize_bytes(buf: &mut [u8]) {
    for b in buf.iter_mut() {
        unsafe { core::ptr::write_volatile(b, 0) };
    }
    core::sync::atomic::compiler_fence(core::sync::atomic::Ordering::SeqCst);
}


// =============================================================================
// 4. SHAKE wrappers — FIPS 202 / FIPS 204 §3.7
// =============================================================================

pub fn shake128(output: &mut [u8], input: &[u8]) {
    let mut h = Shake128::default();
    h.update(input);
    h.finalize_xof().read(output);
}
pub fn shake256(output: &mut [u8], input: &[u8]) {
    let mut h = Shake256::default();
    h.update(input);
    h.finalize_xof().read(output);
}
pub fn shake256_2(output: &mut [u8], a: &[u8], b: &[u8]) {
    let mut h = Shake256::default();
    h.update(a);
    h.update(b);
    h.finalize_xof().read(output);
}
pub fn shake256_3(output: &mut [u8], a: &[u8], b: &[u8], c: &[u8]) {
    let mut h = Shake256::default();
    h.update(a);
    h.update(b);
    h.update(c);
    h.finalize_xof().read(output);
}


